Update docker-exams-Dockerfile

diff --git a/docker-exams-Dockerfile b/docker-exams-Dockerfile
--- a/docker-exams-Dockerfile
+++ b/docker-exams-Dockerfile
@@ -4,6 +4,13 @@ FROM {{DOCKERWINE_DOCKER_IMAGE}}
 RUN apt-get update
 
 # Install ExamPad+.
+if [ ! -f "ExamPad+.msi" ]; then
+    echo "Can't find file ExamPad+.msi - you need to download it from their website."
+    exit 1
+fi
+
+# Copy the (Windows) installer for ExamPad+ into the Docker image.
+COPY ExamPad+.msi /root/ExamPad+.msi
 
 # Copy in the startup scripts. Further setup is done after startup by these scripts rather than here as we create a separate named user in each container instance and need to
 # match up UIDs with the host, which we don't know until container creation time.
